### ISSUE TITLE
Cannot read property 'id' of undefined | cannot find Chrome binary

### ISSUE THREAD

**Issue by P0rc0D10** [MainSilent/Discord-Screenshare#2]
Webdriver started
(node:15688) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: cannot find Chrome binary
    at Object.throwDecodedError (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:642:13)
    at Executor.execute (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:568:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15688) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: cannot find Chrome binary
    at Object.throwDecodedError (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:642:13)
    at Executor.execute (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:568:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:15688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15688) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: cannot find Chrome binary
    at Object.throwDecodedError (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:642:13)
    at Executor.execute (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\selenium-webdriver\lib\http.js:568:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:15688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\structures\Guild.js:307:68)
    at new Guild (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\structures\Guild.js:74:12)
    at ClientDataManager.newGuild (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\ClientDataManager.js:26:19)
    at ReadyHandler.handle (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:20:91)
    at WebSocketPacketManager.handle (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\thispc\Desktop\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:400:28)

**Comment by MainSilent** [comment]
> cannot find Chrome binary

If you have `chromedriver` and `google chrome` installed, Make sure they are the same version.

> Cannot read property 'id' of undefined

This error is because of `Stage channels` since the bot is using discord.js version 11 it doesn't support that, Check the link below for the workaround
https://stackoverflow.com/questions/66894757/discord-js-cannot-read-property-id-of-undefined?rq=1

**Comment by TH3AL3X** [comment]
bro i have a linux VPS without GUI

**Comment by MainSilent** [comment]
You don't need GUI to install chrome

https://askubuntu.com/questions/510056/how-to-install-google-chrome

**Comment by deep2828** [comment]
> > cannot find Chrome binary
> 
> If you have `chromedriver` and `google chrome` installed, Make sure they are the same version.
> 
> > Cannot read property 'id' of undefined
> 
> This error is because of `Stage channels` since the bot is using discord.js version 11 it doesn't support that, Check the link below for the workaround https://stackoverflow.com/questions/66894757/discord-js-cannot-read-property-id-of-undefined?rq=1

I update to v14 still not working 'id' Error bruh
