### ISSUE TITLE
bot cant start

### ISSUE THREAD

**Issue by celiswen** [MainSilent/Discord-Screenshare#25]
```
/home/celiswen/Discord-Screenshare/stream.js:162
    client_url = `file://${__dirname}/client/index.html`
               ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/celiswen/Discord-Screenshare/main.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DiscordStream@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DiscordStream@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/celiswen/.npm/_logs/2022-02-21T13_00_14_701Z-debug.log
```

**Comment by MainSilent** [comment]
Duplicate #3
