### ISSUE TITLE
Error: spawn /home/ray/Tool/Discord-Screenshare/chromedriver EACCES

### ISSUE THREAD

**Issue by ihl7** [MainSilent/Discord-Screenshare#28]
Webdriver started
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/ray/Tool/Discord-Screenshare/chromedriver EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/ray/Tool/Discord-Screenshare/chromedriver',
  path: '/home/ray/Tool/Discord-Screenshare/chromedriver',
  spawnargs: [ '--port=37651' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DiscordStream@1.0.0 start: node main.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DiscordStream@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2022-03-16T12_13_11_131Z-debug.log

**Comment by MainSilent** [comment]
`EACCES` is when your user doesn't have access to a resource, Make sure your user has needed access to the needed resources
