### ISSUE TITLE
This issue when i try running with a token and everything setup correctly

### ISSUE THREAD

**Issue by baguay1** [MainSilent/Discord-Screenshare#3]
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/sircrosar/Desktop/Discord-Screenshare-master/main.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
sircrosar@ubuntu:~/Desktop/Discord-Screenshare-master$

**Comment by baguay1** [comment]
> Also make sure you are using nodejs version 14

i am using nodejs version

**Comment by baguay1** [comment]
> process.env.token

Also what do you mean by this

**Comment by baguay1** [comment]
This is what I have in the env files
token="token here"
owner_id=769446561016184852
log_channel_id=836768745644490765

**Comment by baguay1** [comment]
So i did the exact same thing and its still giving me it

**Comment by MainSilent** [comment]
Sorry, I helped you as much as I could
