### ISSUE TITLE
Everything is fine but this?

### ISSUE THREAD

**Issue by baguay1** [MainSilent/Discord-Screenshare#4]
TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/obama/Desktop/discordss/node_modules/discord.js/src/structures/Guild.js:307:68)
    at new Guild (/home/obama/Desktop/discordss/node_modules/discord.js/src/structures/Guild.js:74:12)
    at ClientDataManager.newGuild (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/ClientDataManager.js:26:19)
    at ReadyHandler.handle (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:20:91)
    at WebSocketPacketManager.handle (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/obama/Desktop/discordss/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/obama/Desktop/discordss/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:390:28)

**Comment by MainSilent** [comment]
Duplicate #2
