### ISSUE TITLE
i need fix

### ISSUE THREAD

**Issue by 34bb** [MainSilent/Discord-Screenshare#5]
node_modules/youtube-dl-wrap/index.js:211
        signal.addEventListener('abort', () => {
               ^

TypeError: Cannot read property 'addEventListener' of null

**Comment by MainSilent** [comment]
Can you send the full error message?
Is `youtube-dl` setup correctly?

**Comment by 34bb** [comment]
└─# npm start                                      

> DiscordStream@1.0.0 start
> node main.js

/home/kali/Desktop/Discord-Screenshare/node_modules/youtube-dl-wrap/index.js:211
        signal?.addEventListener('abort', () => {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/kali/Desktop/Discord-Screenshare/stream.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by MainSilent** [comment]
Duplicate #3
