### ISSUE TITLE
What version of chromedriver ?

### ISSUE THREAD

**Issue by TH3AL3X** [MainSilent/Discord-Screenshare#7]

**Comment by TH3AL3X** [comment]
Cuz i'm getting this
`node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: spawn /root/Discord-Screenshare-master/chromedriver EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /root/Discord-Screenshare-master/chromedriver',
  path: '/root/Discord-Screenshare-master/chromedriver',
  spawnargs: [ '--port=38121' ]
}`

**Comment by TH3AL3X** [comment]
i'm getting this
``Webdriver started
/root/Discord-Screenshare-master/node_modules/selenium-webdriver/lib/error.js:517
    let err = new ctor(data.message)
              ^

WebDriverError: unknown error: cannot find Chrome binary
    at Object.throwDecodedError (/root/Discord-Screenshare-master/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/root/Discord-Screenshare-master/node_modules/selenium-webdriver/lib/http.js:642:13)
    at Executor.execute (/root/Discord-Screenshare-master/node_modules/selenium-webdriver/lib/http.js:568:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  remoteStacktrace: '#0 0x556256fccee3 <unknown>\n' +
    '#1 0x556256a9a608 <unknown>\n' +
    '#2 0x556256abb7f6 <unknown>\n' +
    '#3 0x556256ab946f <unknown>\n' +
    '#4 0x556256af3f45 <unknown>\n' +
    '#5 0x556256aee163 <unknown>\n' +
    '#6 0x556256ac3bfc <unknown>\n' +
    '#7 0x556256ac4c05 <unknown>\n' +
    '#8 0x556256ffebaa <unknown>\n' +
    '#9 0x556257014651 <unknown>\n' +
    '#10 0x556256fffb05 <unknown>\n' +
    '#11 0x556257015a68 <unknown>\n' +
    '#12 0x556256ff405f <unknown>\n' +
    '#13 0x556257030818 <unknown>\n' +
    '#14 0x556257030998 <unknown>\n' +
    '#15 0x55625704beed <unknown>\n' +
    '#16 0x7f60d8ef4609 <unknown>\n'
}``

**Comment by MainSilent** [comment]
Duplicate #2
