### ISSUE TITLE
just run docker and error

### ISSUE THREAD

**Issue by ashroyxi** [MainSilent/Discord-Screenshare#72]
```bash
Webdriver started
/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129:26)
    at Client.login (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/Client.js:335:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

Node.js v17.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn start' returned a non-zero code: 1
```

**Comment by ashroyxi** [comment]
did you insert your token?
like this:
token='kyhgdikyhbsbfsik'
