### ISSUE TITLE
can't run this file on win

### ISSUE THREAD

**Issue by iiElmagicYT** [MainSilent/Discord-Screenshare#74]
what should i do , after i type node main.js
----
      const data_ = data.guild_positions.map((guildId, i) => {
                                         ^

TypeError: Cannot read properties of undefined (reading 'map')
    at ClientUserSettingManager._patch (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js-selfbot-v13\src\managers\ClientUserSettingManager.js:135:42)
    at Object.module.exports [as READY] (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\READY.js:82:18)
    at WebSocketManager.handlePacket (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:478:22)
    at WebSocketShard.onMessage (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:317:10)
    at WebSocket.onMessage (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\ws\lib\websocket.js:1169:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (C:\Users\$\Downloads\Discord-Screenshare-master\Discord-Screenshare-master\node_modules\ws\lib\receiver.js:528:14)

**Comment by kaanosu** [comment]
I don't think this bot is made for win.

**Comment by atomisadev** [comment]
The bot isn't made for Windows, although you can setup WSL on your Windows machine to run it with Docker.
