### ISSUE TITLE
DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by brendonvan** [MainSilent/Discord-Screenshare#79]
/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/rest/RequestHandler.js:350
#21 46.88       throw new DiscordAPIError(data, res.status, request);
#21 46.88             ^
#21 46.88 
#21 46.88 DiscordAPIError: Missing Access
#21 46.88     at RequestHandler.execute (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/rest/RequestHandler.js:350:13)
#21 46.88     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#21 46.88     at async RequestHandler.push (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/rest/RequestHandler.js:51:14)
#21 46.88     at async TextChannel.send (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/structures/interfaces/TextBasedChannel.js:177:15) {
#21 46.88   method: 'post',
#21 46.88   path: '/channels/1083135170619637832/messages',
#21 46.88   code: 50001,
#21 46.88   httpStatus: 403,
#21 46.88   requestData: {
#21 46.88     json: {
#21 46.88       content: 'Command: *help\nSender: !Brendon | 113061263839399936',
#21 46.88       tts: false,
#21 46.88       nonce: undefined,
#21 46.88       embeds: undefined,
#21 46.88       components: undefined,
#21 46.88       username: undefined,
#21 46.88       avatar_url: undefined,
#21 46.88       allowed_mentions: undefined,
#21 46.88       flags: undefined,
#21 46.88       message_reference: undefined,
#21 46.88       attachments: undefined,
#21 46.88       sticker_ids: undefined
#21 46.88     },
#21 46.88     files: []
#21 46.88   }
#21 46.88 }
#21 46.88 
#21 46.88 Node.js v17.9.0
#21 46.91 error Command failed with exit code 1.
#21 46.91 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by brendonvan** [comment]
SOLVED: You just have to give to bot, higher access on your discord server ^
